branch-defaults:
  default:
    environment: api-dev
    group_suffix: null
global:
  application_name: api-dev
  branch: null
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
container_commands:
  01_wsgipass:
    command: 'echo "WSGIPassAuthorization On" >> ../wsgi.conf'